import type { NextPage } from "next";
import { signIn } from "next-auth/react";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title> 문장 - MUNJANG </title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto flex flex-col items-center justify-center min-h-screen p-4">
        <h1 className="text-5xl md:text-[5rem] leading-normal font-extrabold text-gray-800">
          MUNJANG <span className="text-purple-300 font-extrabold"> 문장 </span>
        </h1>
        <div className="p-4" />
        <button
          className="text-3xl bg-purple-300 px-6 py-4 rounded-md font-bold hover:bg-purple-200 duration-300 "
          onClick={() => signIn(undefined, { callbackUrl: "/dashboard" })}
        >
          LOGIN
        </button>
      </main>
    </>
  );
};

export default Home;
